<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

// Получение данных из блока или ViewModel
$itemFirst = $block->escapeHtml($block->getData('item_first'));
$itemSecond = $block->escapeHtml($block->getData('item_second'));
?>

<ul class="nav_list">
    <li><a href="https://magento.test/women.html"><?= $itemFirst ?></a></li>
    <li><a href="https://magento.test/men.html"><?= $itemSecond ?></a></li>
</ul>