<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$quickSearchUrl = $escaper->escapeUrl($helper->getSuggestUrl());
?>
<div class="block block-search">
    <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form"
              action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <?php  if (!empty($queryParams = $additionalSearchFormData->getFormData())): ?>
                <?php foreach ($queryParams as $param): ?>
                    <input type="hidden" name="<?= $escaper->escapeHtmlAttr($param['name']) ?>"
                           value="<?= $escaper->escapeHtmlAttr($param['value']) ?>"/>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                         
                    <input id="search"
                           data-mage-init='{
                            "quickSearch": {
                                "formSelector": "#search_mini_form",
                                "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                "destinationSelector": "#search_autocomplete",
                                "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                            }
                        }'
                           type="text"
                           name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Пошук товару')) ?>"
                           class="input-text"
                           maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                ><div class="search-svg">
                <svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M10.4529 18.0482C14.3891 18.0482 17.5801 14.8989 17.5801 11.0142C17.5801 7.1294 14.3891 3.98018 10.4529 3.98018C6.51657 3.98018 3.32559 7.1294 3.32559 11.0142C3.32559 14.8989 6.51657 18.0482 10.4529 18.0482ZM19.1801 11.0142C19.1801 15.771 15.2728 19.6272 10.4529 19.6272C5.63292 19.6272 1.72559 15.771 1.72559 11.0142C1.72559 6.25731 5.63292 2.40112 10.4529 2.40112C15.2728 2.40112 19.1801 6.25731 19.1801 11.0142Z" fill="#C4C4C4" />
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M16.0693 15.7759C16.3817 15.4676 16.8882 15.4676 17.2006 15.7759L22.2916 20.8002C22.604 21.1085 22.604 21.6084 22.2916 21.9168C21.9791 22.2251 21.4726 22.2251 21.1602 21.9168L16.0693 16.8925C15.7569 16.5842 15.7569 16.0843 16.0693 15.7759Z" fill="#C4C4C4" />
                </svg>
            </div>
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
